### ISSUE TITLE
Syntax break when line ends with repeat-exactly-n-times

### ISSUE THREAD

**Issue by abathur** [lark-parser/lark_syntax#7]
Was goofing around a little and noticed that syntax highlighting breaks when a line ends with the exact repetition form. It seems to get back on track if I add any other literal, rule, the range form, etc.

![screen shot 2018-10-16 at 5 43 25 pm](https://user-images.githubusercontent.com/2548365/47051775-4985a000-d16b-11e8-815d-9acb9607f246.png)

In case it ends up mattering, plugin version 1.2.1, ST3 build 3180, on macos 10.14.

**Comment by danmou** [comment]
Thanks for reporting, I will have a look at it this weekend.
